x-service-common: &service-common
  build:
    context: .
    dockerfile: Dockerfile
    tags:
      - funiq_ai:latest
  image: funiq_ai:latest
  volumes:
    - .:/app
  env_file:
    - .env

services:
  server:
    <<: *service-common
    container_name: funiq_ai_server
    environment:
      MODE: "web"
    ports:
      - "5001:5000"
    depends_on:
      - db
      - redis

  celery_worker:
    <<: *service-common
    container_name: funiq_ai_celery
    environment:
      MODE: "worker"
    depends_on:
      - server
      - redis

  prefect:
      container_name: funiq_ai_prefect
      image: prefecthq/prefect:3-latest
      command: prefect server start --host 0.0.0.0
      ports:
        - "4200:4200"
      env_file:
        - .env
      depends_on:
        - redis
        - db

  db:
    image: postgres:15-alpine
    container_name: ${PGHOST:-funiq_ai_postgres}
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-funiq_ai_db_pass}
      POSTGRES_DB: ${POSTGRES_DB:-funiq_ai_db}
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_HOST_VOLUME:-./volumes/db/data}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    container_name: funiq_ai_redis
    image: redis:6-alpine
    user: redis
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-funiq_ai_redis_pass}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-funiq_ai_redis_pass}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

