/* eslint-disable */
/* prettier-ignore-start */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Register a new account
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email and password
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup Verify
         * @description Verify signup email with verification code
         */
        post: operations["signup_verify_auth_signup_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/activate-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Account
         * @description Send activation email for inactive account
         */
        post: operations["activate_account_auth_activate_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Send password reset email
         */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset password with verification code
         */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Code
         * @description Resend verification code for signup/activation/password reset
         */
        post: operations["resend_verification_code_auth_resend_verification_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/activate-account-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Account Verify
         * @description Verify account activation with verification code
         */
        post: operations["activate_account_verify_auth_activate_account_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout current user and invalidate their refresh token
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Info */
        get: operations["get_account_info_account_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Tenants */
        get: operations["get_account_tenants_account_tenants_get"];
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_account_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Tenant */
        put: operations["update_tenant_account_tenants__tenant_id__put"];
        post?: never;
        /** Delete Tenant */
        delete: operations["delete_tenant_account_tenants__tenant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/tenants/{tenant_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Tenant User */
        post: operations["add_tenant_user_account_tenants__tenant_id__users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/tenants/{tenant_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User Role */
        put: operations["update_user_role_account_tenants__tenant_id__users__user_id__put"];
        post?: never;
        /** Remove Tenant User */
        delete: operations["remove_tenant_user_account_tenants__tenant_id__users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Providers
         * @description Get all available model providers and their configurations from provider schema
         */
        get: operations["get_model_providers_model_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers/{provider_name}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get all available models from a specific provider
         */
        get: operations["get_models_model_providers__provider_name__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers/{provider_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider
         * @description Get a provider configuration by name
         */
        get: operations["get_provider_model_providers__provider_name__get"];
        put?: never;
        /**
         * Save Provider
         * @description Save a provider configuration
         */
        post: operations["save_provider_model_providers__provider_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers/{provider_name}/models/{model_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description Get a model configuration by name
         */
        get: operations["get_model_model_providers__provider_name__models__model_name__get"];
        put?: never;
        /**
         * Save Model
         * @description Save a model configuration
         */
        post: operations["save_model_model_providers__provider_name__models__model_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers/{provider_name}/models/{model_name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Model
         * @description Enable a model and create its associated system app if it doesn't exist
         */
        post: operations["enable_model_model_providers__provider_name__models__model_name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operators
         * @description Get all available operators
         */
        get: operations["get_operators_workflows_operators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Workflow
         * @description Execute a workflow synchronously with specific version.
         *
         *     Args:
         *         workflow_id: Workflow ID
         *         execute_request: Execution request containing input data and version
         */
        post: operations["execute_workflow_workflows__workflow_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Workflow
         * @description Debug a workflow asynchronously using a specific snapshot.
         *
         *     Args:
         *         workflow_id: Workflow ID
         *         debug_request: Debug request containing input data
         */
        post: operations["debug_workflow_workflows__workflow_id__debug_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/static/providers/{provider}/icon/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider Icon
         * @description Get the icon for a specific provider
         *
         *     Args:
         *         provider: The provider name
         *         size: Icon size ('small' or 'large')
         */
        get: operations["get_provider_icon_static_providers__provider__icon__size__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Endpoint */
        get: operations["stream_endpoint_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock/llm/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mock Llm Stream Endpoint */
        get: operations["mock_llm_stream_endpoint_mock_llm_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Language */
            language: string | null;
            status: components["schemas"]["AccountStatus"];
            /** Last Login At */
            last_login_at: string | null;
            /** Last Login Ip */
            last_login_ip: string | null;
            role: components["schemas"]["TenantUserRole"] | null;
            /** Avatar */
            avatar: string | null;
        };
        /**
         * AccountStatus
         * @enum {string}
         */
        AccountStatus: "pending" | "active" | "inactive" | "disabled";
        /**
         * AccountTokenType
         * @enum {string}
         */
        AccountTokenType: "signup_email" | "activate_account_email" | "reset_password_email";
        /** ActivateAccountRequest */
        ActivateAccountRequest: {
            /** Email */
            email: string;
        };
        /** ActivateAccountResponse */
        ActivateAccountResponse: {
            /** Token */
            token: string;
        };
        /** ActivateAccountVerifyRequest */
        ActivateAccountVerifyRequest: {
            /** Token */
            token: string;
            /** Code */
            code: string;
        };
        /** ActivateAccountVerifyResponse */
        ActivateAccountVerifyResponse: {
            /** Access Token */
            access_token: string;
            /** Tenant Id */
            tenant_id: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * ConfigurateMethod
         * @description Enum class for configurate method of provider model.
         * @enum {string}
         */
        ConfigurateMethod: "predefined" | "customizable";
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ForgotPasswordResponse */
        ForgotPasswordResponse: {
            /** Token */
            token: string;
        };
        /** GetModelProvidersResponse */
        GetModelProvidersResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
            /** Total */
            total: number;
        };
        /** GetModelsResponse */
        GetModelsResponse: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Total */
            total: number;
        };
        /** GetOperatorsResponse */
        GetOperatorsResponse: {
            /** Operators */
            operators: components["schemas"]["OperatorEntity"][];
            /** Total */
            total: number;
        };
        /**
         * GlobalUISchemaOptions
         * @description Global UI schema options that can be set globally and used as fallbacks when no field-level value is provided
         */
        GlobalUISchemaOptions: {
            /**
             * Addable
             * @description If false, new items cannot be added to array fields
             */
            addable?: boolean | null;
            /**
             * Copyable
             * @description If true, array items can be copied
             */
            copyable?: boolean | null;
            /**
             * Orderable
             * @description If false, array items cannot be ordered
             */
            orderable?: boolean | null;
            /**
             * Removable
             * @description If false, array items will not be removable
             */
            removable?: boolean | null;
            /**
             * Label
             * @description If false, field labels will be omitted
             */
            label?: boolean | null;
            /**
             * Duplicatekeysuffixseparator
             * @description Separator between key name and integer for duplicate additionalProperties keys
             */
            duplicateKeySuffixSeparator?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JSONSchema
         * @description Generic JSON Schema definition
         */
        JSONSchema: {
            /**
             * Type
             * @default object
             */
            type: string;
            /** Properties */
            properties: {
                [key: string]: components["schemas"]["StringProperty"] | components["schemas"]["NumberProperty"] | Record<string, never>;
            };
            /** Required */
            required?: string[] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Tenant Id */
            tenant_id: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * ModelFeature
         * @description Enum class for llm feature.
         * @enum {string}
         */
        ModelFeature: "tool-call" | "multi-tool-call" | "agent-thought" | "vision" | "stream-tool-call";
        /**
         * ModelInfo
         * @description Model info for a provider
         */
        ModelInfo: {
            /** Model */
            model: string;
            /** Label */
            label: string;
            model_type: components["schemas"]["ModelType"];
            /** Features */
            features?: components["schemas"]["ModelFeature"][] | null;
            configurate_method: components["schemas"]["ConfigurateMethod"];
            /** Model Properties */
            model_properties: Record<string, never>;
            /**
             * Deprecated
             * @default false
             */
            deprecated: boolean;
            parameter_rules_ui_schema?: components["schemas"]["UiSchema"] | null;
            parameter_rules_schema?: components["schemas"]["JSONSchema"] | null;
            pricing?: components["schemas"]["PriceConfig"] | null;
            /** Tenant Id */
            tenant_id: string;
            /** Provider */
            provider: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Is System */
            is_system: boolean;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /**
         * ModelPropertyKey
         * @description Enum class for model property key.
         * @enum {string}
         */
        ModelPropertyKey: "mode" | "context_size" | "max_chunks" | "file_upload_limit" | "supported_file_extensions" | "max_characters_per_chunk" | "default_voice" | "voices" | "word_limit" | "audio_type" | "max_workers";
        /**
         * ModelResponse
         * @description Response schema for getting a model
         */
        ModelResponse: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            model_type: components["schemas"]["ModelType"];
            /** Is System */
            is_system: boolean;
            /** Is Enabled */
            is_enabled: boolean;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /**
         * ModelType
         * @description Enum class for model type.
         * @enum {string}
         */
        ModelType: "llm" | "text-embedding" | "rerank" | "speech2text" | "moderation" | "tts" | "text2img";
        /**
         * NumberProperty
         * @description Number type schema
         */
        NumberProperty: {
            /**
             * Type
             * @default number
             */
            type: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Default */
            default?: unknown | null;
            /** Enum */
            enum?: unknown[] | null;
            /** Const */
            const?: unknown | null;
            /** Minimum */
            minimum?: number | null;
            /** Maximum */
            maximum?: number | null;
            /** Exclusive Minimum */
            exclusive_minimum?: number | null;
            /** Exclusive Maximum */
            exclusive_maximum?: number | null;
            /** Multiple Of */
            multiple_of?: number | null;
        };
        /**
         * OperatorEntity
         * @description Model class for operator schema.
         */
        OperatorEntity: {
            name: components["schemas"]["OperatorName"];
            /** Label */
            label: string;
            type: components["schemas"]["OperatorType"];
            /**
             * Supports Input Stream
             * @default false
             */
            supports_input_stream: boolean;
            output_stream?: components["schemas"]["OutputStream"] | null;
            /** Description */
            description: string;
            output_schema: components["schemas"]["JSONSchema"];
            config_schema: components["schemas"]["JSONSchema"];
            config_ui_schema?: components["schemas"]["UiSchema"] | null;
        };
        /**
         * OperatorName
         * @description Operator type enum defining supported operator types.
         * @enum {string}
         */
        OperatorName: "llm" | "end" | "start";
        /**
         * OperatorType
         * @enum {string}
         */
        OperatorType: "task" | "start" | "end" | "logic";
        /** OutputStream */
        OutputStream: {
            /** Enabled */
            enabled: boolean;
            type: components["schemas"]["OutputStreamType"];
            /** Response Schema */
            response_schema?: Record<string, never> | null;
        };
        /**
         * OutputStreamType
         * @enum {string}
         */
        OutputStreamType: "self" | "external";
        /**
         * PriceConfig
         * @description Model class for pricing info.
         */
        PriceConfig: {
            /** Input */
            input: string;
            /** Output */
            output?: string | null;
            /** Unit */
            unit: string;
            /** Currency */
            currency: string;
        };
        /**
         * ProviderDocs
         * @description Model class for provider docs.
         */
        ProviderDocs: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Provider */
            provider: string;
            /** Label */
            label: string;
            /** Icon */
            icon: {
                [key: string]: string | null;
            } | null;
            /** Supported Model Types */
            supported_model_types: components["schemas"]["ModelType"][];
            docs: components["schemas"]["ProviderDocs"] | null;
            /** Description */
            description?: string | null;
            /** Configurate Methods */
            configurate_methods: components["schemas"]["ConfigurateMethod"][];
            credential_schema: components["schemas"]["JSONSchema"] | null;
            /** Ui Schema */
            ui_schema?: {
                [key: string]: {
                    [key: string]: components["schemas"]["UiSchema"] | null;
                } | null;
            } | null;
        };
        /**
         * ProviderResponse
         * @description Response schema for getting a provider
         */
        ProviderResponse: {
            /** Provider */
            provider: string;
            /** Is System */
            is_system: boolean;
            /** Is Active */
            is_active: boolean;
            /** Credentials */
            credentials?: Record<string, never> | null;
        };
        /** ResendVerificationCodeRequest */
        ResendVerificationCodeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            code_type: components["schemas"]["AccountTokenType"];
        };
        /** ResendVerificationCodeResponse */
        ResendVerificationCodeResponse: {
            /** Token */
            token: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /** ResponseModel */
        ResponseModel: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            /** Data */
            data: unknown;
        };
        /** ResponseModel[AccountResponse] */
        ResponseModel_AccountResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["AccountResponse"];
        };
        /** ResponseModel[ActivateAccountResponse] */
        ResponseModel_ActivateAccountResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ActivateAccountResponse"];
        };
        /** ResponseModel[ActivateAccountVerifyResponse] */
        ResponseModel_ActivateAccountVerifyResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ActivateAccountVerifyResponse"];
        };
        /** ResponseModel[ForgotPasswordResponse] */
        ResponseModel_ForgotPasswordResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ForgotPasswordResponse"];
        };
        /** ResponseModel[GetModelProvidersResponse] */
        ResponseModel_GetModelProvidersResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["GetModelProvidersResponse"];
        };
        /** ResponseModel[GetModelsResponse] */
        ResponseModel_GetModelsResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["GetModelsResponse"];
        };
        /** ResponseModel[GetOperatorsResponse] */
        ResponseModel_GetOperatorsResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["GetOperatorsResponse"];
        };
        /** ResponseModel[LoginResponse] */
        ResponseModel_LoginResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["LoginResponse"];
        };
        /** ResponseModel[ModelResponse] */
        ResponseModel_ModelResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ModelResponse"];
        };
        /** ResponseModel[NoneType] */
        ResponseModel_NoneType_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            /** Data */
            data: null;
        };
        /** ResponseModel[ProviderResponse] */
        ResponseModel_ProviderResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ProviderResponse"];
        };
        /** ResponseModel[ResendVerificationCodeResponse] */
        ResponseModel_ResendVerificationCodeResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["ResendVerificationCodeResponse"];
        };
        /** ResponseModel[SignupResponse] */
        ResponseModel_SignupResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["SignupResponse"];
        };
        /** ResponseModel[SignupVerifyResponse] */
        ResponseModel_SignupVerifyResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["SignupVerifyResponse"];
        };
        /** ResponseModel[TenantResponse] */
        ResponseModel_TenantResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["TenantResponse"];
        };
        /** ResponseModel[UserResponse] */
        ResponseModel_UserResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["UserResponse"];
        };
        /** ResponseModel[WorkflowDebugResponse] */
        ResponseModel_WorkflowDebugResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["WorkflowDebugResponse"];
        };
        /** ResponseModel[WorkflowExecuteResponse] */
        ResponseModel_WorkflowExecuteResponse_: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            data: components["schemas"]["WorkflowExecuteResponse"];
        };
        /** ResponseModel[list[TenantResponse]] */
        ResponseModel_list_TenantResponse__: {
            /**
             * Code
             * @default 0
             */
            code: string;
            /**
             * Msg
             * @default success
             */
            msg: string;
            /** Data */
            data: components["schemas"]["TenantResponse"][];
        };
        /**
         * SaveModelRequest
         * @description Request schema for saving a model
         */
        SaveModelRequest: {
            /** Is System */
            is_system: boolean;
            /** Is Enabled */
            is_enabled?: boolean | null;
        };
        /**
         * SaveProviderRequest
         * @description Request schema for saving a provider
         */
        SaveProviderRequest: {
            /** Is System */
            is_system: boolean;
            /** Credentials */
            credentials?: Record<string, never> | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Invite Code */
            invite_code?: string | null;
        };
        /** SignupResponse */
        SignupResponse: {
            /** Token */
            token: string;
        };
        /** SignupVerifyRequest */
        SignupVerifyRequest: {
            /** Token */
            token: string;
            /** Code */
            code: string;
        };
        /** SignupVerifyResponse */
        SignupVerifyResponse: {
            /** Access Token */
            access_token: string;
            /** Tenant Id */
            tenant_id: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * StringProperty
         * @description String type schema
         */
        StringProperty: {
            /**
             * Type
             * @default string
             */
            type: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Default */
            default?: unknown | null;
            /** Enum */
            enum?: unknown[] | null;
            /** Const */
            const?: unknown | null;
            /** Minlength */
            minLength?: number | null;
            /** Maxlength */
            maxLength?: number | null;
            /** Pattern */
            pattern?: string | null;
            /** Format */
            format?: string | null;
        };
        /** TenantCreateRequest */
        TenantCreateRequest: {
            /** Name */
            name: string;
        };
        /** TenantResponse */
        TenantResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** TenantUpdateRequest */
        TenantUpdateRequest: {
            /** Name */
            name: string;
        };
        /**
         * TenantUserRole
         * @enum {string}
         */
        TenantUserRole: "owner" | "admin" | "member" | "guest";
        /**
         * UIOptionsBaseType
         * @description Base type for UI options
         */
        UIOptionsBaseType: {
            /**
             * Addable
             * @description If false, new items cannot be added to array fields
             */
            addable?: boolean | null;
            /**
             * Copyable
             * @description If true, array items can be copied
             */
            copyable?: boolean | null;
            /**
             * Orderable
             * @description If false, array items cannot be ordered
             */
            orderable?: boolean | null;
            /**
             * Removable
             * @description If false, array items will not be removable
             */
            removable?: boolean | null;
            /**
             * Label
             * @description If false, field labels will be omitted
             */
            label?: boolean | null;
            /**
             * Duplicatekeysuffixseparator
             * @description Separator between key name and integer for duplicate additionalProperties keys
             */
            duplicateKeySuffixSeparator?: string | null;
            /** Classnames */
            classNames?: string | null;
            /** Style */
            style?: Record<string, never> | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Placeholder */
            placeholder?: string | null;
            /** Help */
            help?: string | null;
            /** Autofocus */
            autofocus?: boolean | null;
            /** Autocomplete */
            autocomplete?: string | null;
            /** Disabled */
            disabled?: boolean | null;
            /** Emptyvalue */
            emptyValue?: unknown | null;
            /** Enumdisabled */
            enumDisabled?: (string | number | boolean)[] | null;
            /** Hideerror */
            hideError?: boolean | null;
            /** Readonly */
            readonly?: boolean | null;
            /** Order */
            order?: string[] | null;
            /** Filepreview */
            filePreview?: boolean | null;
            /** Inline */
            inline?: boolean | null;
            /** Inputtype */
            inputType?: string | null;
            /** Rows */
            rows?: number | null;
            submitButtonOptions?: components["schemas"]["UISchemaSubmitButtonOptions"] | null;
            /** Widget */
            widget?: string | null;
            /** Enumnames */
            enumNames?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UISchemaSubmitButtonOptions
         * @description Options for customizing the submit button behavior
         */
        UISchemaSubmitButtonOptions: {
            /**
             * Submittext
             * @description Text to display on submit button
             */
            submitText?: string | null;
            /**
             * Norender
             * @description If true, removes submit button completely
             */
            norender?: boolean | null;
            /**
             * Props
             * @description Additional props to pass to submit button
             */
            props?: Record<string, never> | null;
        };
        /**
         * UiSchema
         * @description UI Schema for React JSON Schema Form
         */
        UiSchema: {
            /** Ui:Addable */
            "ui:addable"?: boolean | null;
            /** Ui:Copyable */
            "ui:copyable"?: boolean | null;
            /** Ui:Orderable */
            "ui:orderable"?: boolean | null;
            /** Ui:Removable */
            "ui:removable"?: boolean | null;
            /** Ui:Label */
            "ui:label"?: boolean | null;
            /** Ui:Duplicatekeysuffixseparator */
            "ui:duplicateKeySuffixSeparator"?: string | null;
            /**
             * Ui:Classnames
             * @description CSS class names to apply to field
             */
            "ui:classNames"?: string | null;
            /**
             * Ui:Style
             * @description Custom styles to apply to field
             */
            "ui:style"?: Record<string, never> | null;
            /**
             * Ui:Title
             * @description Custom title for the field
             */
            "ui:title"?: string | null;
            /**
             * Ui:Description
             * @description Custom description for the field
             */
            "ui:description"?: string | null;
            /**
             * Ui:Placeholder
             * @description Placeholder text for inputs
             */
            "ui:placeholder"?: string | null;
            /**
             * Ui:Help
             * @description Help text shown next to field
             */
            "ui:help"?: string | null;
            /**
             * Ui:Autofocus
             * @description If true, field will be focused on load
             */
            "ui:autofocus"?: boolean | null;
            /**
             * Ui:Autocomplete
             * @description HTML autocomplete attribute
             */
            "ui:autocomplete"?: string | null;
            /**
             * Ui:Disabled
             * @description If true, field will be disabled
             */
            "ui:disabled"?: boolean | null;
            /**
             * Ui:Emptyvalue
             * @description Value to use when input is empty
             */
            "ui:emptyValue"?: unknown | null;
            /**
             * Ui:Enumdisabled
             * @description List of enum values to disable
             */
            "ui:enumDisabled"?: (string | number | boolean)[] | null;
            /**
             * Ui:Hideerror
             * @description If true, hide error display for field
             */
            "ui:hideError"?: boolean | null;
            /**
             * Ui:Readonly
             * @description If true, field will be read-only
             */
            "ui:readonly"?: boolean | null;
            /**
             * Ui:Order
             * @description Custom ordering of object properties
             */
            "ui:order"?: string[] | null;
            /**
             * Ui:Inline
             * @description If true, checkboxes render inline
             */
            "ui:inline"?: boolean | null;
            /**
             * Ui:Widget
             * @description Custom widget to use for field
             */
            "ui:widget"?: string | null;
            /**
             * Ui:Inputtype
             * @description HTML input type
             */
            "ui:inputType"?: string | null;
            /**
             * Ui:Rows
             * @description Number of rows for textarea
             */
            "ui:rows"?: number | null;
            /**
             * Ui:Filepreview
             * @description If true, show file preview
             */
            "ui:filePreview"?: boolean | null;
            "ui:submitButtonOptions"?: components["schemas"]["UISchemaSubmitButtonOptions"] | null;
            /**
             * Ui:Enumnames
             * @description Custom labels for enum values
             */
            "ui:enumNames"?: string[] | null;
            "ui:globalOptions"?: components["schemas"]["GlobalUISchemaOptions"] | null;
            /** Ui:Rootfieldid */
            "ui:rootFieldId"?: string | null;
            /** Ui:Field */
            "ui:field"?: string | null;
            /** Ui:Fieldreplacesanyoroneof */
            "ui:fieldReplacesAnyOrOneOf"?: boolean | null;
            /** Ui:Options */
            "ui:options"?: components["schemas"]["UIOptionsBaseType"] | Record<string, never> | null;
        } & {
            [key: string]: unknown;
        };
        /** UserAddRequest */
        UserAddRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default member */
            role: components["schemas"]["TenantUserRole"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /** Tenant Id */
            tenant_id: string;
            role: components["schemas"]["TenantUserRole"];
        };
        /** UserRoleUpdateRequest */
        UserRoleUpdateRequest: {
            role: components["schemas"]["TenantUserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowDebugRequest */
        WorkflowDebugRequest: {
            /** Input Data */
            input_data: Record<string, never>;
            /**
             * Snapshot Timestamp
             * Format: date-time
             */
            snapshot_timestamp: string;
        };
        /** WorkflowDebugResponse */
        WorkflowDebugResponse: {
            /** Task Id */
            task_id: string;
        };
        /** WorkflowExecuteRequest */
        WorkflowExecuteRequest: {
            /** Input Data */
            input_data: Record<string, never>;
            /** Version */
            version: string;
        };
        /** WorkflowExecuteResponse */
        WorkflowExecuteResponse: {
            /** Result */
            result: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SignupResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_verify_auth_signup_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SignupVerifyResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_account_auth_activate_account_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ActivateAccountResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ForgotPasswordResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_code_auth_resend_verification_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ResendVerificationCodeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_account_verify_auth_activate_account_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateAccountVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ActivateAccountVerifyResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_NoneType_"];
                };
            };
        };
    };
    get_account_info_account_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_AccountResponse_"];
                };
            };
        };
    };
    get_account_tenants_account_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_TenantResponse__"];
                };
            };
        };
    };
    create_tenant_account_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TenantResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_account_tenants__tenant_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TenantResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tenant_account_tenants__tenant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tenant_user_account_tenants__tenant_id__users_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_account_tenants__tenant_id__users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tenant_user_account_tenants__tenant_id__users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_providers_model_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_GetModelProvidersResponse_"];
                };
            };
        };
    };
    get_models_model_providers__provider_name__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_GetModelsResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_model_providers__provider_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ProviderResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_provider_model_providers__provider_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ProviderResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_model_providers__provider_name__models__model_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ModelResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_model_model_providers__provider_name__models__model_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
                model_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ModelResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_model_model_providers__provider_name__models__model_name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ModelResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operators_workflows_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_GetOperatorsResponse_"];
                };
            };
        };
    };
    execute_workflow_workflows__workflow_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_WorkflowExecuteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_workflow_workflows__workflow_id__debug_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDebugRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_WorkflowDebugResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_icon_static_providers__provider__icon__size__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                size: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_endpoint_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mock_llm_stream_endpoint_mock_llm_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}

/* prettier-ignore-end */