import type { components } from '@/types/openapi'

type IComponentsSchemas = components['schemas']

export type IWorkflowInfo = IComponentsSchemas['WorkflowInfo']
export type IWorkflowConfig = IComponentsSchemas['WorkflowConfig']
export type IWorkflowStatus = IComponentsSchemas['WorkflowStatus']
export type IWorkflowVersionInfo = IComponentsSchemas['WorkflowVersionInfo']
export type IWorkflowVersionStatus = IComponentsSchemas['WorkflowVersionStatus']
export type IWorkflowNodeInfo = IComponentsSchemas['WorkflowNodeInfo']
export type IWorkflowEdgeInfo = IComponentsSchemas['WorkflowEdgeInfo']
export type IWorkflowDebugSnapshotInfo = IComponentsSchemas['WorkflowDebugSnapshotInfo']
export type ICreateWorkflowVersionPayload = IComponentsSchemas['CreateWorkflowVersionPayload']
export type ISaveWorkflowRequest = IComponentsSchemas['SaveWorkflowRequest']
export type ISaveWorkflowNodePayload = IComponentsSchemas['SaveWorkflowNodePayload']
export type ISaveWorkflowEdgePayload = IComponentsSchemas['SaveWorkflowEdgePayload']
export type IOperatorEntity = IComponentsSchemas['OperatorEntity']
export type IOperatorName = IComponentsSchemas['OperatorName']
export type IOperatorType = IComponentsSchemas['OperatorType']
export type IOperatorConfigSchema = IComponentsSchemas['OperatorConfigSchema']
export type IOutputStream = IComponentsSchemas['OutputStream']
export type IGetWorkflowDebugSnapshotsResponse = IComponentsSchemas['GetWorkflowDebugSnapshotsResponse']
export type IGetWorkflowVersionsResponse = IComponentsSchemas['GetWorkflowVersionsResponse']
