"""adjust workflow execution & log table

Revision ID: 17edac8e0633
Revises: 9cafceccfefe
Create Date: 2025-04-15 23:34:35.600017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17edac8e0633'
down_revision: Union[str, None] = '9cafceccfefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # first create new enum type
    op.execute("CREATE TYPE executionstates AS ENUM ('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING')")
    
    # Convert status columns
    for table in ['workflow_debug_executions', 'workflow_executions', 
                 'workflow_node_debug_executions', 'workflow_node_executions']:
        op.execute(f"""
            ALTER TABLE {table} 
            ALTER COLUMN status TYPE executionstates 
            USING status::text::executionstates
        """)
    
    # Drop old enum type
    op.execute("DROP TYPE IF EXISTS statetype")

    # Drop indexes if they exist
    op.execute("DROP INDEX IF EXISTS idx_node_execution_flow")
    op.execute("DROP INDEX IF EXISTS idx_node_execution_workflow")
    
    # Drop foreign key constraint if exists
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.table_constraints 
                      WHERE constraint_name = 'workflow_node_executions_execution_id_fkey' 
                      AND table_name = 'workflow_node_executions') THEN
                ALTER TABLE workflow_node_executions DROP CONSTRAINT workflow_node_executions_execution_id_fkey;
            END IF;
        END;
        $$;
    """)

    # Add run_id column as nullable first
    op.add_column('workflow_node_executions', 
                 sa.Column('run_id', sa.UUID(), nullable=True))
    
    # Update the new column with values from execution_id
    op.execute("""
        UPDATE workflow_node_executions 
        SET run_id = execution_id
    """)
    
    # Then make it not nullable
    op.alter_column('workflow_node_executions', 'run_id',
                    existing_type=sa.UUID(),
                    nullable=False,
                    comment='Reference to the parent workflow execution')

    # Create new indexes and foreign key
    op.create_index('idx_node_execution_workflow', 'workflow_node_executions', ['run_id'], unique=False)
    op.create_index('idx_node_execution_node', 'workflow_node_executions', ['node_key'], unique=False)
    op.create_index('idx_node_execution_status', 'workflow_node_executions', ['status'], unique=False)
    op.create_index('idx_node_execution_time', 'workflow_node_executions', ['start_time', 'end_time'], unique=False)
    op.create_foreign_key(None, 'workflow_node_executions', 'workflow_executions', ['run_id'], ['id'], ondelete='CASCADE')

    # Drop old columns
    op.drop_column('workflow_node_executions', 'execution_id')
    op.drop_column('workflow_node_executions', 'task_run_id')
    op.drop_column('workflow_node_executions', 'flow_run_id')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_debug_logs',
    sa.Column('run_id', sa.UUID(), nullable=False, comment='Reference to the debug workflow execution'),
    sa.Column('node_run_id', sa.UUID(), nullable=True, comment='Optional reference to debug node execution, if this is a node-level log'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-incrementing log entry ID'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When the log entry was created'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)'),
    sa.Column('message', sa.String(length=2000), nullable=False, comment='Log message content'),
    sa.Column('context', sa.JSON(), nullable=False, comment='Additional contextual information'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this log entry'),
    sa.ForeignKeyConstraint(['node_run_id'], ['workflow_node_debug_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_debug_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_debug_log_level', 'workflow_debug_logs', ['level'], unique=False)
    op.create_index('idx_wf_debug_log_node_run', 'workflow_debug_logs', ['node_run_id'], unique=False)
    op.create_index('idx_wf_debug_log_node_time', 'workflow_debug_logs', ['node_run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_debug_log_run', 'workflow_debug_logs', ['run_id'], unique=False)
    op.create_index('idx_wf_debug_log_run_time', 'workflow_debug_logs', ['run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_debug_log_timestamp', 'workflow_debug_logs', ['timestamp'], unique=False)
    op.create_table('workflow_execution_logs',
    sa.Column('run_id', sa.UUID(), nullable=False, comment='Reference to the workflow execution'),
    sa.Column('node_run_id', sa.UUID(), nullable=True, comment='Optional reference to node execution, if this is a node-level log'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-incrementing log entry ID'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When the log entry was created'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)'),
    sa.Column('message', sa.String(length=2000), nullable=False, comment='Log message content'),
    sa.Column('context', sa.JSON(), nullable=False, comment='Additional contextual information'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this log entry'),
    sa.ForeignKeyConstraint(['node_run_id'], ['workflow_node_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_log_level', 'workflow_execution_logs', ['level'], unique=False)
    op.create_index('idx_wf_log_node_run', 'workflow_execution_logs', ['node_run_id'], unique=False)
    op.create_index('idx_wf_log_node_time', 'workflow_execution_logs', ['node_run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_log_run', 'workflow_execution_logs', ['run_id'], unique=False)
    op.create_index('idx_wf_log_run_time', 'workflow_execution_logs', ['run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_log_timestamp', 'workflow_execution_logs', ['timestamp'], unique=False)
    op.alter_column('workflow_debug_executions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               type_=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               existing_nullable=False)
    op.drop_index('ix_workflow_debug_executions_workflow_id', table_name='workflow_debug_executions')
    op.drop_constraint('workflow_debug_executions_workflow_id_fkey', 'workflow_debug_executions', type_='foreignkey')
    op.drop_constraint('fk_debug_execution_snapshot', 'workflow_debug_executions', type_='foreignkey')
    op.drop_column('workflow_debug_executions', 'flow_run_id')
    op.alter_column('workflow_executions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for this execution',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the executed workflow',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               type_=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               comment=None,
               existing_comment='Current status of the execution',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the execution started',
               existing_nullable=True)
    op.alter_column('workflow_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the execution completed',
               existing_nullable=True)
    op.alter_column('workflow_executions', 'record_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional execution metadata and results',
               existing_nullable=False)
    op.create_index('idx_execution_created_at', 'workflow_executions', ['created_at'], unique=False)
    op.create_index('idx_execution_status_time', 'workflow_executions', ['status', 'start_time', 'end_time'], unique=False)
    op.drop_constraint('workflow_executions_version_fkey', 'workflow_executions', type_='foreignkey')
    op.drop_constraint('workflow_executions_workflow_id_fkey', 'workflow_executions', type_='foreignkey')
    op.drop_constraint('fk_execution_version', 'workflow_executions', type_='foreignkey')
    op.drop_column('workflow_executions', 'flow_run_id')
    op.add_column('workflow_node_debug_executions', sa.Column('run_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow debug execution'))
    op.alter_column('workflow_node_debug_executions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               type_=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               existing_nullable=False)
    op.drop_index('idx_node_debug_execution_workflow', table_name='workflow_node_debug_executions')
    op.create_index('idx_node_debug_execution_workflow', 'workflow_node_debug_executions', ['run_id'], unique=False)
    op.drop_constraint('workflow_node_debug_executions_execution_id_fkey', 'workflow_node_debug_executions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_node_debug_executions', 'workflow_debug_executions', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_node_debug_executions', 'execution_id')
    op.drop_column('workflow_node_debug_executions', 'task_run_id')
    op.drop_column('workflow_node_debug_executions', 'flow_run_id')
    op.alter_column('workflow_node_executions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for this node execution',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'node_key',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Reference to the executed node',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               type_=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               comment=None,
               existing_comment='Current status of the node execution',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the node execution started',
               existing_nullable=True)
    op.alter_column('workflow_node_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the node execution completed',
               existing_nullable=True)
    op.alter_column('workflow_node_executions', 'record_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional node execution metadata and results',
               existing_nullable=False)
    op.create_foreign_key(None, 'workflow_node_executions', 'workflow_executions', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # first create new enum type
    op.execute("CREATE TYPE statetype AS ENUM ('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING')")
    
    # then use USING clause to convert existing data
    op.execute("""
        ALTER TABLE workflow_debug_executions 
        ALTER COLUMN status TYPE statetype 
        USING status::text::statetype
    """)
    
    op.execute("""
        ALTER TABLE workflow_executions 
        ALTER COLUMN status TYPE statetype 
        USING status::text::statetype
    """)
    
    op.execute("""
        ALTER TABLE workflow_node_debug_executions 
        ALTER COLUMN status TYPE statetype 
        USING status::text::statetype
    """)
    
    op.execute("""
        ALTER TABLE workflow_node_executions 
        ALTER COLUMN status TYPE statetype 
        USING status::text::statetype
    """)
    
    # finally drop new enum type
    op.execute("DROP TYPE IF EXISTS executionstates")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_node_executions', sa.Column('flow_run_id', sa.UUID(), autoincrement=False, nullable=False, comment='Prefect flow run identifier'))
    op.add_column('workflow_node_executions', sa.Column('task_run_id', sa.UUID(), autoincrement=False, nullable=False, comment='Prefect task run identifier'))
    op.add_column('workflow_node_executions', sa.Column('execution_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to the parent workflow execution'))
    op.drop_constraint(None, 'workflow_node_executions', type_='foreignkey')
    op.create_foreign_key('workflow_node_executions_execution_id_fkey', 'workflow_node_executions', 'workflow_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_node_execution_time', table_name='workflow_node_executions')
    op.drop_index('idx_node_execution_status', table_name='workflow_node_executions')
    op.drop_index('idx_node_execution_node', table_name='workflow_node_executions')
    op.create_index('idx_node_execution_workflow', 'workflow_node_executions', ['execution_id'], unique=False)
    op.create_index('idx_node_execution_flow', 'workflow_node_executions', ['flow_run_id', 'status'], unique=False)
    op.alter_column('workflow_node_executions', 'record_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional node execution metadata and results',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the node execution completed',
               existing_nullable=True)
    op.alter_column('workflow_node_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the node execution started',
               existing_nullable=True)
    op.alter_column('workflow_node_executions', 'status',
               existing_type=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               type_=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               comment='Current status of the node execution',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'node_key',
               existing_type=sa.VARCHAR(length=10),
               comment='Reference to the executed node',
               existing_nullable=False)
    op.alter_column('workflow_node_executions', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for this node execution',
               existing_nullable=False)
    op.drop_column('workflow_node_executions', 'run_id')
    op.add_column('workflow_node_debug_executions', sa.Column('flow_run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('workflow_node_debug_executions', sa.Column('task_run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('workflow_node_debug_executions', sa.Column('execution_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to the parent workflow debug execution'))
    op.drop_constraint(None, 'workflow_node_debug_executions', type_='foreignkey')
    op.create_foreign_key('workflow_node_debug_executions_execution_id_fkey', 'workflow_node_debug_executions', 'workflow_debug_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_node_debug_execution_workflow', table_name='workflow_node_debug_executions')
    op.create_index('idx_node_debug_execution_workflow', 'workflow_node_debug_executions', ['execution_id'], unique=False)
    op.alter_column('workflow_node_debug_executions', 'status',
               existing_type=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               type_=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               existing_nullable=False)
    op.drop_column('workflow_node_debug_executions', 'run_id')
    op.add_column('workflow_executions', sa.Column('flow_run_id', sa.UUID(), autoincrement=False, nullable=False, comment='Prefect flow run identifier'))
    op.create_foreign_key('fk_execution_version', 'workflow_executions', 'workflow_versions', ['workflow_id', 'version'], ['workflow_id', 'version'], ondelete='CASCADE')
    op.create_foreign_key('workflow_executions_workflow_id_fkey', 'workflow_executions', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('workflow_executions_version_fkey', 'workflow_executions', 'workflow_versions', ['version'], ['version'], ondelete='CASCADE')
    op.drop_index('idx_execution_status_time', table_name='workflow_executions')
    op.drop_index('idx_execution_created_at', table_name='workflow_executions')
    op.alter_column('workflow_executions', 'record_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional execution metadata and results',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the execution completed',
               existing_nullable=True)
    op.alter_column('workflow_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the execution started',
               existing_nullable=True)
    op.alter_column('workflow_executions', 'status',
               existing_type=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               type_=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               comment='Current status of the execution',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.UUID(),
               comment='Reference to the executed workflow',
               existing_nullable=False)
    op.alter_column('workflow_executions', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for this execution',
               existing_nullable=False)
    op.add_column('workflow_debug_executions', sa.Column('flow_run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_debug_execution_snapshot', 'workflow_debug_executions', 'workflow_snapshots', ['workflow_id', 'snapshot_timestamp'], ['workflow_id', 'snapshot_timestamp'], ondelete='CASCADE')
    op.create_foreign_key('workflow_debug_executions_workflow_id_fkey', 'workflow_debug_executions', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_workflow_debug_executions_workflow_id', 'workflow_debug_executions', ['workflow_id'], unique=False)
    op.alter_column('workflow_debug_executions', 'status',
               existing_type=sa.Enum('CREATED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', 'CANCELLING', name='executionstates'),
               type_=postgresql.ENUM('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'),
               existing_nullable=False)
    op.drop_index('idx_wf_log_timestamp', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_run_time', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_run', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_node_time', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_node_run', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_level', table_name='workflow_execution_logs')
    op.drop_table('workflow_execution_logs')
    op.drop_index('idx_wf_debug_log_timestamp', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_run_time', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_run', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_node_time', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_node_run', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_level', table_name='workflow_debug_logs')
    op.drop_table('workflow_debug_logs')
    # ### end Alembic commands ###
