"""adjust Workflow/app related table

Revision ID: e45d245ee9e4
Revises: 926422f38ab1
Create Date: 2025-04-08 00:36:29.327954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45d245ee9e4'
down_revision: Union[str, None] = '926422f38ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. delete old foreign key
    op.drop_constraint('fk_debug_execution_snapshot', 'workflow_debug_executions', type_='foreignkey')
    
    # 2. create unique constraint on workflow_snapshots table
    op.create_unique_constraint(
        'uq_workflow_snapshots_workflow_id_timestamp',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp']
    )
    
    # 3. create new foreign key constraint
    op.create_foreign_key(
        None, 
        'workflow_debug_executions', 
        'workflows', 
        ['workflow_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp'],
        ['workflow_id', 'snapshot_timestamp'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        None,
        'workflow_snapshots',
        'workflows',
        ['workflow_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. delete foreign key constraint
    op.drop_constraint(None, 'workflow_snapshots', type_='foreignkey')
    op.drop_constraint('fk_debug_execution_snapshot', 'workflow_debug_executions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_debug_executions', type_='foreignkey')
    
    # 2. delete unique constraint
    op.drop_constraint('uq_workflow_snapshots_workflow_id_timestamp', 'workflow_snapshots', type_='unique')
    
    # 3. recreate original foreign key constraint
    op.create_foreign_key(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        'workflow_snapshots',
        ['snapshot_timestamp'],
        ['snapshot_timestamp'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
