"""solve warning

Revision ID: 26914198668b
Revises: 261a0498d705
Create Date: 2025-04-08 08:44:10.478052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26914198668b'
down_revision: Union[str, None] = '261a0498d705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_invite_code_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_invite_code_fkey', 'users', 'tenant_invites', ['invite_code'], ['code'])
    # ### end Alembic commands ###
