"""add tenant_id to workflow

Revision ID: d9f49194fff4
Revises: 32b207263e41
Create Date: 2025-05-02 09:28:43.098064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f49194fff4'
down_revision: Union[str, None] = '32b207263e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Reference to the parent tenant'))
    op.create_index('idx_workflow_tenant', 'workflows', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index('idx_workflow_tenant', table_name='workflows')
    op.drop_column('workflows', 'tenant_id')
    # ### end Alembic commands ###
