"""adjust workflow log table

Revision ID: 24fa5710d0ee
Revises: 17edac8e0633
Create Date: 2025-04-17 14:29:59.910224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fa5710d0ee'
down_revision: Union[str, None] = '17edac8e0633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_debug_log_node_run', table_name='workflow_debug_logs')
    op.drop_index('idx_wf_debug_log_node_time', table_name='workflow_debug_logs')
    op.drop_constraint('workflow_debug_logs_node_run_id_fkey', 'workflow_debug_logs', type_='foreignkey')
    op.drop_column('workflow_debug_logs', 'node_run_id')
    op.drop_index('idx_wf_log_node_run', table_name='workflow_execution_logs')
    op.drop_index('idx_wf_log_node_time', table_name='workflow_execution_logs')
    op.drop_constraint('workflow_execution_logs_node_run_id_fkey', 'workflow_execution_logs', type_='foreignkey')
    op.drop_column('workflow_execution_logs', 'node_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution_logs', sa.Column('node_run_id', sa.UUID(), autoincrement=False, nullable=True, comment='Optional reference to node execution, if this is a node-level log'))
    op.create_foreign_key('workflow_execution_logs_node_run_id_fkey', 'workflow_execution_logs', 'workflow_node_executions', ['node_run_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_wf_log_node_time', 'workflow_execution_logs', ['node_run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_log_node_run', 'workflow_execution_logs', ['node_run_id'], unique=False)
    op.add_column('workflow_debug_logs', sa.Column('node_run_id', sa.UUID(), autoincrement=False, nullable=True, comment='Optional reference to debug node execution, if this is a node-level log'))
    op.create_foreign_key('workflow_debug_logs_node_run_id_fkey', 'workflow_debug_logs', 'workflow_node_debug_executions', ['node_run_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_wf_debug_log_node_time', 'workflow_debug_logs', ['node_run_id', 'timestamp'], unique=False)
    op.create_index('idx_wf_debug_log_node_run', 'workflow_debug_logs', ['node_run_id'], unique=False)
    # ### end Alembic commands ###
