"""add id to workflow edge

Revision ID: 1d02d86d5941
Revises: d9f49194fff4
Create Date: 2025-05-04 22:45:44.671852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d02d86d5941'
down_revision: Union[str, None] = 'd9f49194fff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_edges', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_edges', 'id')
    # ### end Alembic commands ###
