"""update provider/app table

Revision ID: 702f960c775b
Revises: 6e49da419d96
Create Date: 2025-03-04 22:10:21.765209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702f960c775b'
down_revision: Union[str, None] = '6e49da419d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('app_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_apps_app_type'), 'apps', ['app_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_app_type'), table_name='apps')
    op.drop_column('apps', 'app_type')
    # ### end Alembic commands ###
