"""update workflow-node/edge model/model_provider table

Revision ID: 9add0a26c633
Revises: 702f960c775b
Create Date: 2025-03-05 23:22:21.570222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9add0a26c633'
down_revision: Union[str, None] = '702f960c775b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. first handle workflow_node/edge table
    op.drop_constraint('workflow_edges_source_node_key_fkey', 'workflow_edges', type_='foreignkey')
    op.drop_constraint('workflow_edges_target_node_key_fkey', 'workflow_edges', type_='foreignkey')
    op.create_foreign_key('fk_edge_source_node', 'workflow_edges', 'workflow_nodes', ['workflow_id', 'source_node_key'], ['workflow_id', 'node_key'])
    op.create_foreign_key('fk_edge_target_node', 'workflow_edges', 'workflow_nodes', ['workflow_id', 'target_node_key'], ['workflow_id', 'node_key'])
    op.create_unique_constraint('unique_workflow_edge', 'workflow_edges', ['workflow_id', 'edge_key'])
    op.drop_index('ix_workflow_nodes_node_key', table_name='workflow_nodes')
    
    # 2. handle model table
    op.drop_constraint('models_provider_fkey', 'models', type_='foreignkey')
    op.drop_index('ix_model_providers_provider', table_name='model_providers')
    op.create_index(op.f('ix_model_providers_provider'), 'model_providers', ['provider'], unique=False)
    op.create_foreign_key('fk_model_provider', 'models', 'model_providers', ['tenant_id', 'provider'], ['tenant_id', 'provider'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workflow_nodes_node_key', 'workflow_nodes', ['node_key'], unique=True)
    op.drop_constraint('fk_edge_target_node', 'workflow_edges', type_='foreignkey')
    op.drop_constraint('fk_edge_source_node', 'workflow_edges', type_='foreignkey')
    op.create_foreign_key('workflow_edges_target_node_key_fkey', 'workflow_edges', 'workflow_nodes', ['target_node_key'], ['node_key'])
    op.create_foreign_key('workflow_edges_source_node_key_fkey', 'workflow_edges', 'workflow_nodes', ['source_node_key'], ['node_key'])
    op.drop_constraint('unique_workflow_edge', 'workflow_edges', type_='unique')
    op.create_index('ix_workflow_edges_workflow_id', 'workflow_edges', ['workflow_id'], unique=False)
    op.drop_constraint('fk_model_provider', 'models', type_='foreignkey')
    op.create_foreign_key('models_provider_fkey', 'models', 'model_providers', ['provider'], ['provider'], ondelete='CASCADE')
    op.create_index('ix_models_tenant_id', 'models', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_model_providers_provider'), table_name='model_providers')
    op.create_index('ix_model_providers_provider', 'model_providers', ['provider'], unique=True)
    op.create_index('ix_model_providers_tenant_id', 'model_providers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
