"""adjust WorkflowVersion table

Revision ID: 745654576f72
Revises: ca61e79396b7
Create Date: 2025-04-04 02:13:22.144150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745654576f72'
down_revision: Union[str, None] = 'ca61e79396b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_versions', sa.Column('snapshot', sa.JSON(), nullable=False, comment='Snapshot of the workflow version'))
    op.drop_column('workflow_versions', 'commit_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_versions', sa.Column('commit_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False, comment='Git commit hash associated with this version'))
    op.drop_column('workflow_versions', 'snapshot')
    # ### end Alembic commands ###
