"""add app/model_provider/mode/workflow/node/edge table

Revision ID: 9783d6fd5062
Revises: 55db90ca20f2
Create Date: 2025-03-03 22:59:03.917251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9783d6fd5062'
down_revision: Union[str, None] = '55db90ca20f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('credential_schema', sa.JSON(), nullable=True),
    sa.Column('supported_model_types', sa.JSON(), nullable=True),
    sa.Column('docs', sa.JSON(), nullable=True),
    sa.Column('icon', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='unique_tenant_provider')
    )
    op.create_index(op.f('ix_model_providers_is_system'), 'model_providers', ['is_system'], unique=False)
    op.create_index(op.f('ix_model_providers_provider'), 'model_providers', ['provider'], unique=True)
    op.create_index(op.f('ix_model_providers_tenant_id'), 'model_providers', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='unique_tenant_workflow')
    )
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('apps',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'is_system', name='unique_tenant_app'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_index(op.f('ix_apps_is_system'), 'apps', ['is_system'], unique=False)
    op.create_index(op.f('ix_apps_tenant_id'), 'apps', ['tenant_id'], unique=False)
    op.create_table('models',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('parameter_rules_schema', sa.JSON(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider'], ['model_providers.provider'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'model', name='unique_tenant_provider_model')
    )
    op.create_index(op.f('ix_models_is_enabled'), 'models', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_models_is_system'), 'models', ['is_system'], unique=False)
    op.create_index(op.f('ix_models_last_used_at'), 'models', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_models_model'), 'models', ['model'], unique=False)
    op.create_index(op.f('ix_models_model_type'), 'models', ['model_type'], unique=False)
    op.create_index(op.f('ix_models_provider'), 'models', ['provider'], unique=False)
    op.create_index(op.f('ix_models_tenant_id'), 'models', ['tenant_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'node_key', name='unique_workflow_node')
    )
    op.create_index(op.f('ix_workflow_nodes_node_key'), 'workflow_nodes', ['node_key'], unique=True)
    op.create_index(op.f('ix_workflow_nodes_workflow_id'), 'workflow_nodes', ['workflow_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('edge_key', sa.String(length=255), nullable=False),
    sa.Column('source_node_key', sa.String(length=255), nullable=False),
    sa.Column('target_node_key', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_key'], ['workflow_nodes.node_key'], ),
    sa.ForeignKeyConstraint(['target_node_key'], ['workflow_nodes.node_key'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edges_workflow_id'), 'workflow_edges', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_edges_workflow_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_workflow_nodes_workflow_id'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_node_key'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index(op.f('ix_models_tenant_id'), table_name='models')
    op.drop_index(op.f('ix_models_provider'), table_name='models')
    op.drop_index(op.f('ix_models_model_type'), table_name='models')
    op.drop_index(op.f('ix_models_model'), table_name='models')
    op.drop_index(op.f('ix_models_last_used_at'), table_name='models')
    op.drop_index(op.f('ix_models_is_system'), table_name='models')
    op.drop_index(op.f('ix_models_is_enabled'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_apps_tenant_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_is_system'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_model_providers_tenant_id'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_provider'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_is_system'), table_name='model_providers')
    op.drop_table('model_providers')
    # ### end Alembic commands ###
