"""adjust workflow version/snapshot & message related tables 

Revision ID: af9c6b064888
Revises: 16e8bcf809a2
Create Date: 2025-04-20 13:42:52.530924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9c6b064888'
down_revision: Union[str, None] = '16e8bcf809a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_versions', sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow'))
    op.drop_index('idx_conversation_app', table_name='conversations')
    op.drop_constraint('conversations_app_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'version')
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'app_id')
    op.add_column('messages', sa.Column('app_version_id', sa.UUID(), nullable=True, comment='Reference to the specific app version'))
    op.create_index('idx_message_app_version', 'messages', ['app_version_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'app_versions', ['app_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('workflow_snapshots', sa.Column('end_node_key', sa.String(length=10), nullable=False))
    op.add_column('workflow_snapshots', sa.Column('start_node_key', sa.String(length=10), nullable=False))
    op.add_column('workflow_versions', sa.Column('end_node_key', sa.String(length=10), nullable=False, comment='Reference to the end node'))
    op.add_column('workflow_versions', sa.Column('start_node_key', sa.String(length=10), nullable=False, comment='Reference to the start node'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_versions', 'start_node_key')
    op.drop_column('workflow_versions', 'end_node_key')
    op.drop_column('workflow_snapshots', 'start_node_key')
    op.drop_column('workflow_snapshots', 'end_node_key')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('idx_message_app_version', table_name='messages')
    op.drop_column('messages', 'app_version_id')
    op.add_column('conversations', sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to the application'))
    op.add_column('conversations', sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Conversation summary'))
    op.add_column('conversations', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Application version used'))
    op.create_foreign_key('conversations_app_id_fkey', 'conversations', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_conversation_app', 'conversations', ['app_id'], unique=False)
    op.drop_column('app_versions', 'workflow_id')
    # ### end Alembic commands ###
