"""adjust model provider table

Revision ID: 776c79b7a905
Revises: cb2856b4ac2a
Create Date: 2025-04-27 23:14:40.339708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776c79b7a905'
down_revision: Union[str, None] = 'cb2856b4ac2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_tenant_provider', 'model_providers', ['tenant_id', 'provider'])
    op.drop_constraint('model_providers_tenant_id_fkey', 'model_providers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('model_providers_tenant_id_fkey', 'model_providers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('unique_tenant_provider', 'model_providers', type_='unique')
    # ### end Alembic commands ###
