"""update model provider & model table

Revision ID: 7e2265e442df
Revises: 9ea2e0c330e8
Create Date: 2025-04-24 22:48:12.261018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2265e442df'
down_revision: Union[str, None] = '9ea2e0c330e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customized_models',
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('model_properties', sa.JSON(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('parameter_rules_ui_schema', sa.JSON(), nullable=True),
    sa.Column('parameter_rules_schema', sa.JSON(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_customized_model_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_index(op.f('ix_customized_models_model_type'), 'customized_models', ['model_type'], unique=False)
    op.create_index(op.f('ix_customized_models_provider'), 'customized_models', ['provider'], unique=False)
    op.drop_index('ix_models_configurate_method', table_name='models')
    op.drop_index('ix_models_created_at', table_name='models')
    op.drop_index('ix_models_is_enabled', table_name='models')
    op.drop_index('ix_models_is_system', table_name='models')
    op.drop_index('ix_models_last_used_at', table_name='models')
    op.drop_index('ix_models_model', table_name='models')
    op.drop_index('ix_models_model_type', table_name='models')
    op.drop_index('ix_models_provider', table_name='models')
    op.drop_index('ix_models_updated_at', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_model_providers_created_at', table_name='model_providers')
    op.drop_index('ix_model_providers_is_system', table_name='model_providers')
    op.drop_index('ix_model_providers_provider', table_name='model_providers')
    op.drop_index('ix_model_providers_updated_at', table_name='model_providers')
    op.drop_constraint('unique_tenant_provider', 'model_providers', type_='unique')
    op.create_foreign_key('fk_model_provider_tenant', 'model_providers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_providers', 'updated_at')
    op.drop_column('model_providers', 'docs')
    op.drop_column('model_providers', 'id')
    op.drop_column('model_providers', 'supported_model_types')
    op.drop_column('model_providers', 'credential_schema')
    op.drop_column('model_providers', 'description')
    op.drop_column('model_providers', 'is_system')
    op.drop_column('model_providers', 'icon')
    op.drop_column('model_providers', 'label')
    op.drop_column('model_providers', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_providers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('model_providers', sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('icon', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('model_providers', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('credential_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('supported_model_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('model_providers', sa.Column('docs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model_providers', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_model_provider_tenant', 'model_providers', type_='foreignkey')
    op.create_unique_constraint('unique_tenant_provider', 'model_providers', ['tenant_id', 'provider'])
    op.create_index('ix_model_providers_updated_at', 'model_providers', ['updated_at'], unique=False)
    op.create_index('ix_model_providers_provider', 'model_providers', ['provider'], unique=False)
    op.create_index('ix_model_providers_is_system', 'model_providers', ['is_system'], unique=False)
    op.create_index('ix_model_providers_created_at', 'model_providers', ['created_at'], unique=False)
    op.create_table('models',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pricing', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameter_rules_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deprecated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('configurate_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameter_rules_ui_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'provider'], ['model_providers.tenant_id', 'model_providers.provider'], name='fk_model_provider', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='models_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='models_pkey'),
    sa.UniqueConstraint('tenant_id', 'provider', 'model', name='unique_tenant_provider_model')
    )
    op.create_index('ix_models_updated_at', 'models', ['updated_at'], unique=False)
    op.create_index('ix_models_provider', 'models', ['provider'], unique=False)
    op.create_index('ix_models_model_type', 'models', ['model_type'], unique=False)
    op.create_index('ix_models_model', 'models', ['model'], unique=False)
    op.create_index('ix_models_last_used_at', 'models', ['last_used_at'], unique=False)
    op.create_index('ix_models_is_system', 'models', ['is_system'], unique=False)
    op.create_index('ix_models_is_enabled', 'models', ['is_enabled'], unique=False)
    op.create_index('ix_models_created_at', 'models', ['created_at'], unique=False)
    op.create_index('ix_models_configurate_method', 'models', ['configurate_method'], unique=False)
    op.drop_index(op.f('ix_customized_models_provider'), table_name='customized_models')
    op.drop_index(op.f('ix_customized_models_model_type'), table_name='customized_models')
    op.drop_table('customized_models')
    # ### end Alembic commands ###
