"""add EncryptedJSON/type & adjust some table

Revision ID: cb2856b4ac2a
Revises: 0862f12a5ea1
Create Date: 2025-04-27 23:08:36.658650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb2856b4ac2a'
down_revision: Union[str, None] = '0862f12a5ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customized_models_model_type', table_name='customized_models')
    op.drop_index('ix_customized_models_provider', table_name='customized_models')
    op.drop_table('customized_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customized_models',
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pricing', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameter_rules_ui_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameter_rules_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deprecated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='customized_models_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_customized_model_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model', name='customized_models_pkey')
    )
    op.create_index('ix_customized_models_provider', 'customized_models', ['provider'], unique=False)
    op.create_index('ix_customized_models_model_type', 'customized_models', ['model_type'], unique=False)
    # ### end Alembic commands ###
