"""execution record add created_at created_by

Revision ID: 261a0498d705
Revises: f346f25735a4
Create Date: 2025-04-08 08:02:07.856499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261a0498d705'
down_revision: Union[str, None] = 'f346f25735a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workflow_executions', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('workflow_node_debug_executions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workflow_node_debug_executions', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('workflow_node_executions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workflow_node_executions', sa.Column('created_by', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_node_executions', 'created_by')
    op.drop_column('workflow_node_executions', 'created_at')
    op.drop_column('workflow_node_debug_executions', 'created_by')
    op.drop_column('workflow_node_debug_executions', 'created_at')
    op.drop_column('workflow_executions', 'created_by')
    op.drop_column('workflow_executions', 'created_at')
    # ### end Alembic commands ###
