"""update log table

Revision ID: 0862f12a5ea1
Revises: f7b022c9f806
Create Date: 2025-04-26 12:49:25.582958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0862f12a5ea1'
down_revision: Union[str, None] = 'f7b022c9f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_debug_logs', 'message',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_comment='Log message content',
               existing_nullable=False)
    op.alter_column('workflow_execution_logs', 'message',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_comment='Log message content',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_execution_logs', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_comment='Log message content',
               existing_nullable=False)
    op.alter_column('workflow_debug_logs', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_comment='Log message content',
               existing_nullable=False)
    # ### end Alembic commands ###
