"""update model table

Revision ID: 6e49da419d96
Revises: 9783d6fd5062
Create Date: 2025-03-04 09:33:26.779210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e49da419d96'
down_revision: Union[str, None] = '9783d6fd5062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('configurate_method', sa.String(length=50), nullable=False))
    op.add_column('models', sa.Column('model_properties', sa.JSON(), nullable=True))
    op.add_column('models', sa.Column('parameter_rules_ui_schema', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_models_configurate_method'), 'models', ['configurate_method'], unique=False)
    op.drop_column('models', 'mode')
    op.drop_column('models', 'context_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('context_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_models_configurate_method'), table_name='models')
    op.drop_column('models', 'parameter_rules_ui_schema')
    op.drop_column('models', 'model_properties')
    op.drop_column('models', 'configurate_method')
    # ### end Alembic commands ###
