"""update tables

Revision ID: 56478bc7be34
Revises: 7e2265e442df
Create Date: 2025-04-25 23:57:05.897612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56478bc7be34'
down_revision: Union[str, None] = '7e2265e442df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('support_file', sa.Boolean(), nullable=False, comment='Whether the application supports file'))
    op.add_column('apps', sa.Column('support_image', sa.Boolean(), nullable=False, comment='Whether the application supports image'))
    op.add_column('apps', sa.Column('support_audio', sa.Boolean(), nullable=False, comment='Whether the application supports audio'))
    op.add_column('apps', sa.Column('support_thinking', sa.Boolean(), nullable=False, comment='Whether the application supports thinking'))
    op.add_column('apps', sa.Column('support_tool', sa.Boolean(), nullable=False, comment='Whether the application supports tool'))
    op.drop_index('idx_app_system', table_name='apps')
    op.drop_column('apps', 'is_system')
    op.add_column('conversations', sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Reference to the tenant'))
    op.create_index('idx_conversation_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customized_models', 'credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customized_models', sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index('idx_conversation_tenant', table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    op.add_column('apps', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether this is a system application'))
    op.create_index('idx_app_system', 'apps', ['is_system'], unique=False)
    op.drop_column('apps', 'support_tool')
    op.drop_column('apps', 'support_thinking')
    op.drop_column('apps', 'support_audio')
    op.drop_column('apps', 'support_image')
    op.drop_column('apps', 'support_file')
    # ### end Alembic commands ###
