"""adjust WorkflowNode table

Revision ID: 57789c140d13
Revises: 79cfee661e99
Create Date: 2025-04-07 19:42:57.202082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57789c140d13'
down_revision: Union[str, None] = '79cfee661e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'output_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON schema defining expected node output format'))
    # ### end Alembic commands ###
