"""adjust Workflow execute/debug related table

Revision ID: 926422f38ab1
Revises: 57789c140d13
Create Date: 2025-04-08 00:18:43.796627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '926422f38ab1'
down_revision: Union[str, None] = '57789c140d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_debug_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow_debug_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='When the execution started')
    op.alter_column('workflow_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='When the execution completed')
    op.alter_column('workflow_node_debug_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow_node_debug_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow_node_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='When the node execution started')
    op.alter_column('workflow_node_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='When the node execution completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_node_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='When the node execution completed')
    op.alter_column('workflow_node_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='When the node execution started')
    op.alter_column('workflow_node_debug_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow_node_debug_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='When the execution completed')
    op.alter_column('workflow_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='When the execution started')
    op.alter_column('workflow_debug_executions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow_debug_executions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
