"""version of app/workflow can be none

Revision ID: f346f25735a4
Revises: a3087b686be2
Create Date: 2025-04-08 00:52:45.275782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f346f25735a4'
down_revision: Union[str, None] = 'a3087b686be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. delete dependent foreign key constraint
    op.drop_constraint(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        type_='foreignkey'
    )
    
    # 2. delete old unique constraint
    op.drop_constraint(
        'uq_workflow_snapshots_workflow_id_timestamp',
        'workflow_snapshots',
        type_='unique'
    )
    
    # 3. create new unique constraint (keep composite key unique)
    op.create_unique_constraint(
        'uq_workflow_snapshots_composite',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp']
    )
    
    # 4. recreate foreign key constraint (reference new unique constraint)
    op.create_foreign_key(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp'],
        ['workflow_id', 'snapshot_timestamp'],
        ondelete='CASCADE'
    )
    
    # 5. modify version field to be nullable
    op.alter_column(
        'apps',
        'version',
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment='Current version number'
    )
    op.alter_column(
        'workflows',
        'version',
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment='Current version number of the workflow'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. restore version field to be non-nullable
    op.alter_column(
        'workflows',
        'version',
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment='Current version number of the workflow'
    )
    op.alter_column(
        'apps',
        'version',
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment='Current version number'
    )
    
    # 2. delete existing foreign key constraint
    op.drop_constraint(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        type_='foreignkey'
    )
    
    # 3. delete new unique constraint
    op.drop_constraint(
        'uq_workflow_snapshots_composite',
        'workflow_snapshots',
        type_='unique'
    )
    
    # 4. recreate original unique constraint
    op.create_unique_constraint(
        'uq_workflow_snapshots_workflow_id_timestamp',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp']
    )
    
    # 5. recreate dependent foreign key constraint
    op.create_foreign_key(
        'fk_debug_execution_snapshot',
        'workflow_debug_executions',
        'workflow_snapshots',
        ['workflow_id', 'snapshot_timestamp'],
        ['workflow_id', 'snapshot_timestamp'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
