"""create workflow/app related tables

Revision ID: ca61e79396b7
Revises: 9add0a26c633
Create Date: 2025-04-03 23:20:37.578389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca61e79396b7'
down_revision: Union[str, None] = '9add0a26c633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum types first
    workflow_node_type = sa.Enum('LLM', 'END', 'START', name='workflownodetype')
    workflow_node_type.create(op.get_bind(), checkfirst=True)

    workflow_status_type = sa.Enum('DRAFT', 'PUBLISHED', name='workflowstatus')
    workflow_status_type.create(op.get_bind(), checkfirst=True)

    op.drop_constraint('fk_edge_source_node', 'workflow_edges', type_='foreignkey')
    op.drop_constraint('fk_edge_target_node', 'workflow_edges', type_='foreignkey')
    op.drop_constraint('workflow_edges_workflow_id_fkey', 'workflow_edges', type_='foreignkey')

    op.drop_constraint('unique_workflow_node', 'workflow_nodes', type_='unique')
    op.drop_index('ix_workflow_nodes_workflow_id', table_name='workflow_nodes', if_exists=True)
    
    op.create_index('idx_node_workflow', 'workflow_nodes', ['workflow_id'], unique=False)
    op.create_unique_constraint('uq_workflow_node', 'workflow_nodes', ['workflow_id', 'node_key'])
    op.create_unique_constraint('uq_workflow_node_name', 'workflow_nodes', ['workflow_id', 'name'])

    op.create_foreign_key('fk_edge_source_node', 'workflow_edges', 'workflow_nodes',
        ['workflow_id', 'source_node_key'], ['workflow_id', 'node_key'], ondelete='CASCADE')
    op.create_foreign_key('fk_edge_target_node', 'workflow_edges', 'workflow_nodes',
        ['workflow_id', 'target_node_key'], ['workflow_id', 'node_key'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_edges', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_snapshots',
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow'),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_timestamp')
    )
    op.create_index('idx_workflow_snapshot_workflow', 'workflow_snapshots', ['workflow_id'], unique=False)
    op.create_table('workflow_debug_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False, comment='Timestamp of the workflow snapshot used for debugging'),
    sa.Column('flow_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('record_info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_timestamp'], ['workflow_snapshots.snapshot_timestamp'], name='fk_debug_execution_snapshot', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debug_execution_snapshot', 'workflow_debug_executions', ['workflow_id', 'snapshot_timestamp'], unique=False)
    op.create_index('idx_debug_execution_workflow', 'workflow_debug_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_debug_executions_workflow_id'), 'workflow_debug_executions', ['workflow_id'], unique=False)
    op.create_table('app_versions',
    sa.Column('app_id', sa.UUID(), nullable=False, comment='Reference to the parent application'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Version number'),
    sa.Column('workflow_version', sa.String(length=50), nullable=False, comment='Associated workflow version'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='Publication timestamp'),
    sa.Column('published_by', sa.UUID(), nullable=False, comment='User who published this version'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED', name='appversionstatus'), nullable=False, comment='Version status'),
    sa.Column('snapshot', sa.JSON(), nullable=False, comment='Version snapshot data'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_published', 'app_versions', ['published_at'], unique=False)
    op.create_index('idx_version_status', 'app_versions', ['status'], unique=False)
    op.create_index(op.f('ix_app_versions_created_at'), 'app_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_versions_updated_at'), 'app_versions', ['updated_at'], unique=False)
    op.create_index('uk_app_version', 'app_versions', ['app_id', 'version'], unique=True)
    op.create_table('conversations',
    sa.Column('app_id', sa.UUID(), nullable=False, comment='Reference to the application'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Application version used'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Conversation name'),
    sa.Column('summary', sa.String(length=1000), nullable=True, comment='Conversation summary'),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='conversationstatus'), nullable=False, comment='Conversation status'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the conversation'),
    sa.Column('updated_by', sa.UUID(), nullable=False, comment='User who updated the conversation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_app', 'conversations', ['app_id'], unique=False)
    op.create_index('idx_conversation_status', 'conversations', ['status'], unique=False)
    op.create_index('idx_conversation_user', 'conversations', ['created_by'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_table('workflow_node_debug_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow debug execution'),
    sa.Column('node_key', sa.String(length=10), nullable=False),
    sa.Column('flow_run_id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('record_info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_debug_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_debug_execution_workflow', 'workflow_node_debug_executions', ['execution_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the message'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Reference to the parent conversation'),
    sa.Column('message_from', sa.Enum('USER', 'APP', name='messagefrom'), nullable=False, comment='Message source (user or app)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the message was created'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the message (only for user messages)'),
    sa.Column('message', sa.JSON(), nullable=False, comment='Message content in JSON format'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_from', 'messages', ['message_from'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('version', sa.String(length=50), nullable=False, comment='Version identifier (e.g., v1.0.0)'),
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow'),
    sa.Column('status', sa.Enum('DEPRECATED', 'ARCHIVED', 'INACTIVE', 'ACTIVE', name='workflowversionstatus'), nullable=False, comment='Current status of the workflow version'),
    sa.Column('commit_hash', sa.String(length=40), nullable=False, comment='Git commit hash associated with this version'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='Description of changes in this version'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='Timestamp when this version was published'),
    sa.Column('published_by', sa.UUID(), nullable=False, comment='User ID who published this version'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_version')
    )
    op.create_index('idx_workflow_version_status', 'workflow_versions', ['status'], unique=False)
    op.create_index('idx_workflow_version_workflow', 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this execution'),
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Reference to the executed workflow'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Version of the workflow that was executed'),
    sa.Column('flow_run_id', sa.UUID(), nullable=False, comment='Prefect flow run identifier'),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'), nullable=False, comment='Current status of the execution'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='When the execution started'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='When the execution completed'),
    sa.Column('record_info', sa.JSON(), nullable=False, comment='Additional execution metadata and results'),
    sa.ForeignKeyConstraint(['version'], ['workflow_versions.version'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id', 'version'], ['workflow_versions.workflow_id', 'workflow_versions.version'], name='fk_execution_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_start_time', 'workflow_executions', ['start_time'], unique=False)
    op.create_index('idx_execution_version', 'workflow_executions', ['workflow_id', 'version'], unique=False)
    op.create_index('idx_execution_workflow_status', 'workflow_executions', ['workflow_id', 'status'], unique=False)
    op.create_table('workflow_node_executions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this node execution'),
    sa.Column('execution_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow execution'),
    sa.Column('node_key', sa.String(length=10), nullable=False, comment='Reference to the executed node'),
    sa.Column('flow_run_id', sa.UUID(), nullable=False, comment='Prefect flow run identifier'),
    sa.Column('task_run_id', sa.UUID(), nullable=False, comment='Prefect task run identifier'),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'), nullable=False, comment='Current status of the node execution'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='When the node execution started'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='When the node execution completed'),
    sa.Column('record_info', sa.JSON(), nullable=False, comment='Additional node execution metadata and results'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_execution_flow', 'workflow_node_executions', ['flow_run_id', 'status'], unique=False)
    op.create_index('idx_node_execution_workflow', 'workflow_node_executions', ['execution_id'], unique=False)
    op.add_column('accounts', sa.Column('account_type', sa.String(length=50), nullable=True, comment='Type of account (system or regular)'))
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_updated_at'), 'accounts', ['updated_at'], unique=False)
    op.add_column('apps', sa.Column('version', sa.String(length=50), nullable=False, comment='Current version number'))
    op.add_column('apps', sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='Last execution timestamp'))
    op.alter_column('apps', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Reference to the tenant',
               existing_nullable=False)
    op.alter_column('apps', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='Name of the application',
               existing_nullable=False)
    op.alter_column('apps', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment='Description of the application',
               existing_nullable=True)
    op.alter_column('apps', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='Whether this is a system application',
               existing_nullable=False)
    op.alter_column('apps', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who created the application')
    op.alter_column('apps', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who updated the application')
    op.drop_constraint('apps_workflow_id_key', 'apps', type_='unique')
    op.drop_index('ix_apps_app_type', table_name='apps')
    op.drop_index('ix_apps_is_system', table_name='apps')
    op.drop_index('ix_apps_tenant_id', table_name='apps')
    op.drop_constraint('unique_tenant_app', 'apps', type_='unique')
    op.create_index('idx_app_system', 'apps', ['is_system'], unique=False)
    op.create_index('idx_app_tenant', 'apps', ['tenant_id'], unique=False)
    op.create_index('idx_app_version', 'apps', ['version'], unique=False)
    op.create_index(op.f('ix_apps_created_at'), 'apps', ['created_at'], unique=False)
    op.create_index(op.f('ix_apps_updated_at'), 'apps', ['updated_at'], unique=False)
    op.create_index('uk_app_tenant_name', 'apps', ['tenant_id', 'name'], unique=True)
    op.drop_constraint('apps_created_by_fkey', 'apps', type_='foreignkey')
    op.drop_constraint('apps_tenant_id_fkey', 'apps', type_='foreignkey')
    op.drop_constraint('apps_updated_by_fkey', 'apps', type_='foreignkey')
    op.drop_constraint('apps_workflow_id_fkey', 'apps', type_='foreignkey')
    op.create_foreign_key(None, 'apps', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('apps', 'workflow_id')
    op.drop_column('apps', 'app_type')
    op.drop_index('ix_model_providers_tenant_id', table_name='model_providers')
    op.create_index(op.f('ix_model_providers_created_at'), 'model_providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_providers_updated_at'), 'model_providers', ['updated_at'], unique=False)
    op.drop_index('ix_models_tenant_id', table_name='models')
    op.create_index(op.f('ix_models_created_at'), 'models', ['created_at'], unique=False)
    op.create_index(op.f('ix_models_updated_at'), 'models', ['updated_at'], unique=False)
    op.create_index(op.f('ix_o_auth_providers_created_at'), 'o_auth_providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_o_auth_providers_updated_at'), 'o_auth_providers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tenant_invites_created_at'), 'tenant_invites', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_invites_updated_at'), 'tenant_invites', ['updated_at'], unique=False)
    op.add_column('tenants', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_updated_at'), 'tenants', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.add_column('workflow_edges', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('workflow_edges', sa.Column('updated_by', sa.UUID(), nullable=False))
    op.alter_column('workflow_edges', 'edge_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='Unique identifier for the edge within its workflow',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'workflow_id',
               existing_type=sa.UUID(),
               comment='Reference to the parent workflow',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'source_node_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='Reference to the source node',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'target_node_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='Reference to the target node',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Edge metadata including UI properties (path style, labels)',
               existing_nullable=True)
    op.drop_index('ix_workflow_edges_workflow_id', table_name='workflow_edges')
    op.drop_constraint('unique_workflow_edge', 'workflow_edges', type_='unique')
    op.create_index('idx_edge_workflow_source', 'workflow_edges', ['workflow_id', 'source_node_key'], unique=False)
    op.create_index('idx_edge_workflow_target', 'workflow_edges', ['workflow_id', 'target_node_key'], unique=False)
    op.create_index(op.f('ix_workflow_edges_created_at'), 'workflow_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_edges_updated_at'), 'workflow_edges', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_workflow_edge', 'workflow_edges', ['workflow_id', 'edge_key'])
    op.create_unique_constraint('uq_workflow_edge_nodes', 'workflow_edges', ['workflow_id', 'source_node_key', 'target_node_key'])
    op.drop_constraint('workflow_edges_workflow_id_fkey', 'workflow_edges', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_edges', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_edges', 'edge_type')
    op.drop_column('workflow_edges', 'id')
    op.drop_column('workflow_edges', 'config')
    op.add_column('workflow_nodes', sa.Column('description', sa.String(length=255), nullable=True, comment="Optional description of the node's purpose"))
    op.add_column('workflow_nodes', sa.Column('extended_config', sa.JSON(), nullable=True, comment='Extended configuration specific to node type (e.g., LLM parameters)'))
    op.add_column('workflow_nodes', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('workflow_nodes', sa.Column('updated_by', sa.UUID(), nullable=False))
    op.alter_column('workflow_nodes', 'node_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='Unique identifier for the node within its workflow',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'workflow_id',
               existing_type=sa.UUID(),
               comment='Reference to the parent workflow',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'node_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LLM', 'END', 'START', name='workflownodetype'),
               postgresql_using='node_type::workflownodetype',
               comment='Type of operation this node performs',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='Display name of the node',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Node metadata including UI properties (position, style, etc)',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Core configuration for node operation (parameters, settings)',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON schema defining expected node output format',
               existing_nullable=True)
    op.drop_index('ix_workflow_nodes_workflow_id', table_name='workflow_nodes', if_exists=True)
    op.create_index(op.f('ix_workflow_nodes_created_at'), 'workflow_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_updated_at'), 'workflow_nodes', ['updated_at'], unique=False)
    op.drop_constraint('workflow_nodes_workflow_id_fkey', 'workflow_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_nodes', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_nodes', 'id')
    op.add_column('workflows', sa.Column('app_id', sa.UUID(), nullable=False, comment='Reference to the parent application'))
    op.add_column('workflows', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='workflowstatus'), nullable=False, comment='Current status of the workflow'))
    op.add_column('workflows', sa.Column('version', sa.String(length=50), nullable=False, comment='Current version number of the workflow'))
    op.alter_column('workflows', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='Display name of the workflow',
               existing_nullable=False)
    op.alter_column('workflows', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               comment="Optional description of the workflow's purpose",
               existing_nullable=True)
    op.drop_index('ix_workflows_tenant_id', table_name='workflows')
    op.drop_constraint('unique_tenant_workflow', 'workflows', type_='unique')
    op.create_index('idx_workflow_status_created', 'workflows', ['status', 'created_at'], unique=False)
    op.create_index('idx_workflow_updated', 'workflows', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflows_created_at'), 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_updated_at'), 'workflows', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_workflow_app_name', 'workflows', ['app_id', 'name'])
    op.drop_constraint('workflows_tenant_id_fkey', 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflows', 'tenant_id')

    accounts = sa.table('accounts',
        sa.column('id', sa.String),
        sa.column('account_type', sa.String),
        sa.column('email', sa.String)
    )

    op.execute(
        accounts.update()
        .where(accounts.c.account_type.is_(None))
        .values(account_type='regular')
    )
    
    op.alter_column('accounts', 'account_type',
        existing_type=sa.String(length=50),
        nullable=False,
        existing_comment='Type of account (system or regular)'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key('workflows_tenant_id_fkey', 'workflows', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('uq_workflow_app_name', 'workflows', type_='unique')
    op.drop_index(op.f('ix_workflows_updated_at'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_at'), table_name='workflows')
    op.drop_index('idx_workflow_updated', table_name='workflows')
    op.drop_index('idx_workflow_status_created', table_name='workflows')
    op.create_unique_constraint('unique_tenant_workflow', 'workflows', ['tenant_id', 'name'])
    op.create_index('ix_workflows_tenant_id', 'workflows', ['tenant_id'], unique=False)
    op.alter_column('workflows', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment="Optional description of the workflow's purpose",
               existing_nullable=True)
    op.alter_column('workflows', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name of the workflow',
               existing_nullable=False)
    op.drop_column('workflows', 'version')
    op.drop_column('workflows', 'status')
    op.drop_column('workflows', 'app_id')
    op.add_column('workflow_nodes', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_nodes', type_='foreignkey')
    op.create_foreign_key('workflow_nodes_workflow_id_fkey', 'workflow_nodes', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint('uq_workflow_node_name', 'workflow_nodes', type_='unique')
    op.drop_index(op.f('ix_workflow_nodes_updated_at'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_created_at'), table_name='workflow_nodes')
    op.drop_index('idx_node_workflow', table_name='workflow_nodes')
    op.create_unique_constraint('unique_workflow_node', 'workflow_nodes', ['workflow_id', 'node_key'])
    op.create_index('ix_workflow_nodes_workflow_id', 'workflow_nodes', ['workflow_id'], unique=False)
    op.alter_column('workflow_nodes', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON schema defining expected node output format',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Core configuration for node operation (parameters, settings)',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Node metadata including UI properties (position, style, etc)',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name of the node',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'node_type',
               existing_type=sa.Enum('LLM', 'END', 'START', name='workflownodetype'),
               type_=sa.String(50),
               postgresql_using='node_type::varchar'
    )
    op.alter_column('workflow_nodes', 'workflow_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the parent workflow',
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'node_key',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique identifier for the node within its workflow',
               existing_nullable=False)
    op.drop_column('workflow_nodes', 'updated_by')
    op.drop_column('workflow_nodes', 'created_by')
    op.drop_column('workflow_nodes', 'extended_config')
    op.drop_column('workflow_nodes', 'description')
    op.add_column('workflow_edges', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow_edges', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('workflow_edges', sa.Column('edge_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('fk_edge_target_node', 'workflow_edges', type_='foreignkey')
    op.drop_constraint(None, 'workflow_edges', type_='foreignkey')
    op.drop_constraint('fk_edge_source_node', 'workflow_edges', type_='foreignkey')
    op.create_foreign_key('fk_edge_target_node', 'workflow_edges', 'workflow_nodes', ['workflow_id', 'target_node_key'], ['workflow_id', 'node_key'])
    op.create_foreign_key('workflow_edges_workflow_id_fkey', 'workflow_edges', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key('fk_edge_source_node', 'workflow_edges', 'workflow_nodes', ['workflow_id', 'source_node_key'], ['workflow_id', 'node_key'])
    op.drop_constraint('uq_workflow_edge_nodes', 'workflow_edges', type_='unique')
    op.drop_constraint('uq_workflow_edge', 'workflow_edges', type_='unique')
    op.drop_index(op.f('ix_workflow_edges_updated_at'), table_name='workflow_edges')
    op.drop_index(op.f('ix_workflow_edges_created_at'), table_name='workflow_edges')
    op.drop_index('idx_edge_workflow_target', table_name='workflow_edges')
    op.drop_index('idx_edge_workflow_source', table_name='workflow_edges')
    op.create_unique_constraint('unique_workflow_edge', 'workflow_edges', ['workflow_id', 'edge_key'])
    op.create_index('ix_workflow_edges_workflow_id', 'workflow_edges', ['workflow_id'], unique=False)
    op.alter_column('workflow_edges', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Edge metadata including UI properties (path style, labels)',
               existing_nullable=True)
    op.alter_column('workflow_edges', 'target_node_key',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference to the target node',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'source_node_key',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference to the source node',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'workflow_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the parent workflow',
               existing_nullable=False)
    op.alter_column('workflow_edges', 'edge_key',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique identifier for the edge within its workflow',
               existing_nullable=False)
    op.drop_column('workflow_edges', 'updated_by')
    op.drop_column('workflow_edges', 'created_by')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_tenants_updated_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_column('tenants', 'deleted_by')
    op.drop_column('tenants', 'deleted_at')
    op.drop_index(op.f('ix_tenant_invites_updated_at'), table_name='tenant_invites')
    op.drop_index(op.f('ix_tenant_invites_created_at'), table_name='tenant_invites')
    op.drop_index(op.f('ix_o_auth_providers_updated_at'), table_name='o_auth_providers')
    op.drop_index(op.f('ix_o_auth_providers_created_at'), table_name='o_auth_providers')
    op.drop_index(op.f('ix_models_updated_at'), table_name='models')
    op.drop_index(op.f('ix_models_created_at'), table_name='models')
    op.create_index('ix_models_tenant_id', 'models', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_model_providers_updated_at'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_created_at'), table_name='model_providers')
    op.create_index('ix_model_providers_tenant_id', 'model_providers', ['tenant_id'], unique=False)
    op.add_column('apps', sa.Column('app_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('apps', sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.create_foreign_key('apps_workflow_id_fkey', 'apps', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key('apps_updated_by_fkey', 'apps', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('apps_tenant_id_fkey', 'apps', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('apps_created_by_fkey', 'apps', 'users', ['created_by'], ['id'])
    op.drop_index('uk_app_tenant_name', table_name='apps')
    op.drop_index(op.f('ix_apps_updated_at'), table_name='apps')
    op.drop_index(op.f('ix_apps_created_at'), table_name='apps')
    op.drop_index('idx_app_version', table_name='apps')
    op.drop_index('idx_app_tenant', table_name='apps')
    op.drop_index('idx_app_system', table_name='apps')
    op.create_unique_constraint('unique_tenant_app', 'apps', ['tenant_id', 'name', 'is_system'])
    op.create_index('ix_apps_tenant_id', 'apps', ['tenant_id'], unique=False)
    op.create_index('ix_apps_is_system', 'apps', ['is_system'], unique=False)
    op.create_index('ix_apps_app_type', 'apps', ['app_type'], unique=False)
    op.create_unique_constraint('apps_workflow_id_key', 'apps', ['workflow_id'])
    op.alter_column('apps', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='User who updated the application')
    op.alter_column('apps', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='User who created the application')
    op.alter_column('apps', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this is a system application',
               existing_nullable=False)
    op.alter_column('apps', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Description of the application',
               existing_nullable=True)
    op.alter_column('apps', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the application',
               existing_nullable=False)
    op.alter_column('apps', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the tenant',
               existing_nullable=False)
    op.drop_column('apps', 'last_run_at')
    op.drop_column('apps', 'version')
    op.drop_index(op.f('ix_accounts_updated_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_column('accounts', 'deleted_by')
    op.drop_column('accounts', 'deleted_at')
    op.drop_column('accounts', 'account_type')
    op.drop_index('idx_node_execution_workflow', table_name='workflow_node_executions')
    op.drop_index('idx_node_execution_flow', table_name='workflow_node_executions')
    op.drop_table('workflow_node_executions')
    op.drop_index('idx_execution_workflow_status', table_name='workflow_executions')
    op.drop_index('idx_execution_version', table_name='workflow_executions')
    op.drop_index('idx_execution_start_time', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_workflow_version_workflow', table_name='workflow_versions')
    op.drop_index('idx_workflow_version_status', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index('idx_message_from', table_name='messages')
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_node_debug_execution_workflow', table_name='workflow_node_debug_executions')
    op.drop_table('workflow_node_debug_executions')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('idx_conversation_user', table_name='conversations')
    op.drop_index('idx_conversation_status', table_name='conversations')
    op.drop_index('idx_conversation_app', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('uk_app_version', table_name='app_versions')
    op.drop_index(op.f('ix_app_versions_updated_at'), table_name='app_versions')
    op.drop_index(op.f('ix_app_versions_created_at'), table_name='app_versions')
    op.drop_index('idx_version_status', table_name='app_versions')
    op.drop_index('idx_version_published', table_name='app_versions')
    op.drop_table('app_versions')
    op.drop_index(op.f('ix_workflow_debug_executions_workflow_id'), table_name='workflow_debug_executions')
    op.drop_index('idx_debug_execution_workflow', table_name='workflow_debug_executions')
    op.drop_index('idx_debug_execution_snapshot', table_name='workflow_debug_executions')
    op.drop_table('workflow_debug_executions')
    op.drop_index('idx_workflow_snapshot_workflow', table_name='workflow_snapshots')
    op.drop_table('workflow_snapshots')

    op.alter_column('workflow_nodes', 'node_type',
        type_=sa.String(50),
        existing_type=sa.Enum('LLM', 'END', 'START', name='workflownodetype'),
        postgresql_using='node_type::varchar'
    )

    sa.Enum(name='workflownodetype').drop(op.get_bind())
    sa.Enum(name='workflowstatus').drop(op.get_bind())

    # ### end Alembic commands ###
