"""adjust Workflow table

Revision ID: a3087b686be2
Revises: e45d245ee9e4
Create Date: 2025-04-08 00:44:27.595123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3087b686be2'
down_revision: Union[str, None] = 'e45d245ee9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('workflows', sa.Column('updated_by', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'updated_by')
    op.drop_column('workflows', 'created_by')
    # ### end Alembic commands ###
