"""update app/conversation/message/workflow related tables

Revision ID: 32b207263e41
Revises: adbf884e998e
Create Date: 2025-04-30 23:50:49.860685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32b207263e41'
down_revision: Union[str, None] = 'adbf884e998e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_debug_snapshots',
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False, comment='Snapshot data'),
    sa.Column('snapshot_hash', sa.String(length=256), nullable=False),
    sa.Column('start_node_key', sa.String(length=10), nullable=False),
    sa.Column('end_node_key', sa.String(length=10), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Reference to the parent workflow'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'snapshot_timestamp', name='uq_workflow_debug_snapshots_composite')
    )
    op.drop_index('idx_workflow_snapshot_workflow', table_name='workflow_snapshots')
    op.drop_table('workflow_snapshots')
    op.add_column('accounts', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the record'))
    op.add_column('accounts', sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who updated the record'))
    op.alter_column('apps', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='Name of the application',
               existing_nullable=False)
    op.alter_column('apps', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who created the record',
               existing_comment='User who created the application')
    op.alter_column('apps', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who updated the record',
               existing_comment='User who updated the application')
    op.drop_column('apps', 'last_run_at')
    op.drop_column('apps', 'support_audio')
    op.drop_column('apps', 'support_file')
    op.drop_column('apps', 'support_image')
    op.drop_column('apps', 'support_tool')
    op.drop_column('apps', 'support_thinking')
    op.execute('ALTER TABLE conversations ALTER COLUMN last_message_id TYPE UUID USING NULL')
    op.alter_column('conversations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who created the record',
               existing_comment='User who created the conversation')
    op.alter_column('conversations', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who updated the record',
               existing_comment='User who updated the conversation')
    op.alter_column('messages', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Reference to the workflow',
               existing_comment='Reference to the specific workflow')
    op.alter_column('messages', 'workflow_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Workflow version')
    op.alter_column('messages', 'workflow_run_id',
               existing_type=sa.UUID(),
               comment='App execution id',
               existing_comment='Workflow version id',
               existing_nullable=True)
    op.add_column('messages', sa.Column('new_id', sa.UUID(), nullable=True))
    op.execute("UPDATE messages SET new_id = gen_random_uuid()")
    op.drop_constraint('messages_pkey', 'messages', type_='primary')
    op.drop_column('messages', 'id')
    op.alter_column('messages', 'new_id', new_column_name='id')
    op.alter_column('messages', 'id', nullable=False)
    op.create_primary_key('messages_pkey', 'messages', ['id'])
    op.alter_column('messages', 'created_by',
               existing_type=sa.UUID(),
               comment='User who created the record',
               existing_comment='User who created the message (only for user messages)',
               existing_nullable=True)
    op.alter_column('messages', 'updated_by',
               existing_type=sa.UUID(),
               comment='User who updated the record',
               existing_comment='User who updated the message (only for user messages)',
               existing_nullable=True)
    op.drop_constraint('messages_workflow_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.add_column('o_auth_providers', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the record'))
    op.add_column('o_auth_providers', sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who updated the record'))
    op.add_column('tenant_invites', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the record'))
    op.add_column('tenant_invites', sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who updated the record'))
    op.add_column('tenants', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the record'))
    op.add_column('tenants', sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who updated the record'))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the record'))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who updated the record'))
    op.alter_column('workflow_edges', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who created the record')
    op.alter_column('workflow_edges', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who updated the record')
    op.drop_constraint('uq_workflow_edge_nodes', 'workflow_edges', type_='unique')
    op.add_column('workflow_nodes', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('workflow_nodes', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment="Optional description of the node's purpose",
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who created the record')
    op.alter_column('workflow_nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who updated the record')
    op.drop_constraint('uq_workflow_node_name', 'workflow_nodes', type_='unique')
    op.add_column('workflow_versions', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('workflow_versions', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('idx_workflow_version_workflow', table_name='workflow_versions')
    op.add_column('workflows', sa.Column('config', sa.JSON(), nullable=True, comment='Workflow configuration'))
    op.alter_column('workflows', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who created the record')
    op.alter_column('workflows', 'updated_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment='User who updated the record')
    op.drop_constraint('uq_workflow_app_name', 'workflows', type_='unique')
    op.drop_column('workflows', 'description')
    op.drop_column('workflows', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Display name of the workflow'))
    op.add_column('workflows', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="Optional description of the workflow's purpose"))
    op.create_unique_constraint('uq_workflow_app_name', 'workflows', ['app_id', 'name'])
    op.alter_column('workflows', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who updated the record')
    op.alter_column('workflows', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who created the record')
    op.drop_column('workflows', 'config')
    op.create_index('idx_workflow_version_workflow', 'workflow_versions', ['workflow_id'], unique=False)
    op.alter_column('workflow_versions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('workflow_versions', 'id')
    op.create_unique_constraint('uq_workflow_node_name', 'workflow_nodes', ['workflow_id', 'name'])
    op.alter_column('workflow_nodes', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who updated the record')
    op.alter_column('workflow_nodes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who created the record')
    op.alter_column('workflow_nodes', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment="Optional description of the node's purpose",
               existing_nullable=True)
    op.drop_column('workflow_nodes', 'id')
    op.create_unique_constraint('uq_workflow_edge_nodes', 'workflow_edges', ['workflow_id', 'source_node_key', 'target_node_key'])
    op.alter_column('workflow_edges', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who updated the record')
    op.alter_column('workflow_edges', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='User who created the record')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenant_invites', 'updated_by')
    op.drop_column('tenant_invites', 'created_by')
    op.drop_column('o_auth_providers', 'updated_by')
    op.drop_column('o_auth_providers', 'created_by')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_workflow_id_fkey', 'messages', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.alter_column('messages', 'updated_by',
               existing_type=sa.UUID(),
               comment='User who updated the message (only for user messages)',
               existing_comment='User who updated the record',
               existing_nullable=True)
    op.alter_column('messages', 'created_by',
               existing_type=sa.UUID(),
               comment='User who created the message (only for user messages)',
               existing_comment='User who created the record',
               existing_nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('messages', 'workflow_run_id',
               existing_type=sa.UUID(),
               comment='Workflow version id',
               existing_comment='App execution id',
               existing_nullable=True)
    op.alter_column('messages', 'workflow_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Workflow version')
    op.alter_column('messages', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Reference to the specific workflow',
               existing_comment='Reference to the workflow')
    op.alter_column('conversations', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who updated the conversation',
               existing_comment='User who updated the record')
    op.alter_column('conversations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who created the conversation',
               existing_comment='User who created the record')
    op.alter_column('conversations', 'last_message_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_comment='Last message id',
               existing_nullable=True)
    op.add_column('apps', sa.Column('support_thinking', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the application supports thinking'))
    op.add_column('apps', sa.Column('support_tool', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the application supports tool'))
    op.add_column('apps', sa.Column('support_image', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the application supports image'))
    op.add_column('apps', sa.Column('support_file', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the application supports file'))
    op.add_column('apps', sa.Column('support_audio', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the application supports audio'))
    op.add_column('apps', sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Last execution timestamp'))
    op.alter_column('apps', 'updated_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who updated the application',
               existing_comment='User who updated the record')
    op.alter_column('apps', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='User who created the application',
               existing_comment='User who created the record')
    op.alter_column('apps', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_comment='Name of the application',
               existing_nullable=False)
    op.drop_column('accounts', 'updated_by')
    op.drop_column('accounts', 'created_by')
    op.create_table('workflow_snapshots',
    sa.Column('snapshot_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to the parent workflow'),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Snapshot data'),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('snapshot_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('end_node_key', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('start_node_key', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_snapshots_workflow_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_timestamp', name='workflow_snapshots_pkey'),
    sa.UniqueConstraint('workflow_id', 'snapshot_timestamp', name='uq_workflow_snapshots_composite')
    )
    op.create_index('idx_workflow_snapshot_workflow', 'workflow_snapshots', ['workflow_id'], unique=False)
    op.drop_table('workflow_debug_snapshots')
    # ### end Alembic commands ###
