"""update account table

Revision ID: f7b022c9f806
Revises: 56478bc7be34
Create Date: 2025-04-26 00:24:45.948656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7b022c9f806'
down_revision: Union[str, None] = '56478bc7be34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_account_type', table_name='accounts')
    op.drop_column('accounts', 'account_type')
    op.alter_column('workflow_snapshots', 'snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Snapshot data',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Version identifier (e.g., v1.0.0)',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'status',
               existing_type=postgresql.ENUM('DEPRECATED', 'ARCHIVED', 'INACTIVE', 'ACTIVE', name='workflowversionstatus'),
               comment=None,
               existing_comment='Current status of the workflow version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Description of changes in this version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when this version was published',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'published_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID who published this version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Snapshot data',
               existing_comment='Snapshot of the workflow version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'start_node_key',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Reference to the start node',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'end_node_key',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Reference to the end node',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_versions', 'end_node_key',
               existing_type=sa.VARCHAR(length=10),
               comment='Reference to the end node',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'start_node_key',
               existing_type=sa.VARCHAR(length=10),
               comment='Reference to the start node',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Snapshot of the workflow version',
               existing_comment='Snapshot data',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'published_by',
               existing_type=sa.UUID(),
               comment='User ID who published this version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this version was published',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment='Description of changes in this version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'status',
               existing_type=postgresql.ENUM('DEPRECATED', 'ARCHIVED', 'INACTIVE', 'ACTIVE', name='workflowversionstatus'),
               comment='Current status of the workflow version',
               existing_nullable=False)
    op.alter_column('workflow_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Version identifier (e.g., v1.0.0)',
               existing_nullable=False)
    op.alter_column('workflow_snapshots', 'snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Snapshot data',
               existing_nullable=False)
    op.add_column('accounts', sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of account (system or regular)'))
    op.create_index('ix_accounts_account_type', 'accounts', ['account_type'], unique=False)
    # ### end Alembic commands ###
