"""adjust WorkflowVersion table

Revision ID: 79cfee661e99
Revises: 745654576f72
Create Date: 2025-04-06 21:05:32.581409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cfee661e99'
down_revision: Union[str, None] = '745654576f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_versions', sa.Column('snapshot_hash', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_versions', 'snapshot_hash')
    # ### end Alembic commands ###
